package_attributes: ["name", "author", "author_email",
                     "description", "license", "copyright"]

component_attributes: ["package", "node"]

component_interface:
    publisher: ["name"]
    cyclicPublisher: ["name", "frequency"]
    dynParameter: ["name"]
