package_attributes: ["name", "author", "author_email", "description", "license", "copyright"]
component_attributes: ["name"]

component_interface:
    serviceServer: ["name", "type", "description"]
    parameter: ["name", "type", "value", "description"]
    dynParameter: ["name", "type", "value", "description"]
    listener: ["name", "description"]
    broadcaster: ["name", "description"]
