package_attributes: ["name", "author", "author_email", "description", "license", "copyright"]
component_attributes: ["name"]

component_interface:
  msg: ["name", "description"]
  srv: ["name", "description"]
  action: ["name", "description"]
