package_attributes: ["name", "author", "author_email", "description", "license", "copyright"]
node_attributes: ["name"]

node_interface:
  msg: ["name", "description"]
  srv: ["name", "description"]
  action: ["name", "description"]
